### ISSUE TITLE
Back button bug

### ISSUE THREAD

**Issue by jacmaes** [CodyHouse/cd-page-transition-v1-changelog#1]
Hi there, 

In your demo page, when clicking on the "Go to page two" button, the transition to page 2 happens as expected. BUT if I hit the browser back button to return to the previous page, the animation gets stuck midway. Here's a screenshot demostrating the issue:

![stuck](https://user-images.githubusercontent.com/1206842/106129886-f9c31b00-6160-11eb-9a29-bc6e4ee45385.png)

Tested on the latest version of Chrome and Firefox.

**Comment by claudia-romano** [comment]
Hi Jacques, thanks for the heads-up! We have just pushed an updated version of the Page Transition Plugin (which is a dependency for the Page Transition v1 component) that fixes the issue. 

You can get the updated js code here:
https://codyhouse.co/ds/components/app/page-transition-plugin

Cheers!

**Comment by jacmaes** [comment]
Great, thanks!
