### ISSUE TITLE
How to reinit components instructions aren't clear.

### ISSUE THREAD

**Issue by iamrobert** [CodyHouse/cd-page-transition-v1-changelog#2]
Hi,

The plugin is similar to barba.js which I have worked with before.

When we add [Lazy Load component](https://codyhouse.co/ds/components/info/lazy-load) - it doesn't reinit on the pages once its in PJAX. When we go to page 2 - it doesn't load. However on refresh it works. 

My guess is because CodyHouse uses progressive js - the header script doesn't get called again:

<script>document.getElementsByTagName("html")[0].className += " js";</script>

Here's my code:

<img data-src="images/mega-site-nav-img-1.jpg" loading="lazy" alt="" class="lazy">
 
```     
afterEnter: function(newContent, link) {
      
    var lazyEl = newContent.getElementsByClassName('lazy');
    for(var i = 0; i < lazyEl.length; i++) {
      new LazyLoad();
    }  
       
  },
 
```
 
My guess is also the Mega Nav fails as well - which is what I also want to work.

Could you help please?

**Comment by claudia-romano** [comment]
Hi Robert,
you can reinit all your JS at once reloading your page js file. More info here:
https://codyhouse.co/ds/components/info/page-transition-plugin#content-initialization

Cheers!

**Comment by iamrobert** [comment]
Thanks:
I resolved it this way by putting the mega-menu outside `<main>`.

I run this to update the active class on my menu:

```
    var parser = new DOMParser();
    var content = parser.parseFromString(newPageRawHTML, "text/html");
    var navs = content.querySelectorAll(".mega-nav li");
    document.querySelectorAll(".mega-nav li").forEach(function (el, index) {
      var classes = navs[index].classList.value;
      el.setAttribute("class", classes);
    });
```
